/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./Pages/**/*.{cshtml,cshtml.cs}",
    "./wwwroot/**/*.js",
    "./src/**/*.{jsx,js}",
  ],
  safelist: ["annap-type-display", "annap-type-narrative", "annap-type-functional"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-ui)"],
        display: ["var(--font-display)"],
        narrative: ["var(--font-ui)"],
        mono: ["var(--font-code)"],
        number: ["var(--font-code)"],
        "annap-correspond-display": ["var(--font-display)"],
        "annap-correspond-narrative": ["var(--font-ui)"],
      },
      colors: {
        annap: {
          void: "rgb(var(--annap-void-rgb) / <alpha-value>)",
          depth: "rgb(var(--annap-depth-rgb) / <alpha-value>)",
          dusk: "rgb(var(--annap-dusk-rgb) / <alpha-value>)",
          ember: "rgb(var(--annap-ember-rgb) / <alpha-value>)",
          amber: "rgb(var(--annap-amber-rgb) / <alpha-value>)",
          gold: "rgb(var(--annap-gold-rgb) / <alpha-value>)",
          copper: "rgb(var(--annap-copper-rgb) / <alpha-value>)",
          slate: "rgb(var(--annap-slate-rgb) / <alpha-value>)",
          teal: "rgb(var(--annap-teal-rgb) / <alpha-value>)",
          canvas: "rgb(var(--annap-text-primary-rgb) / <alpha-value>)",
        },
        paper: {
          letter: "var(--paper-letter)",
          aged: "var(--paper-aged)",
          fold: "var(--paper-fold)",
          desk: "var(--paper-desk)",
        },
        ink: {
          deep: "var(--ink-deep)",
          primary: "var(--ink-primary)",
          secondary: "var(--ink-secondary)",
          tertiary: "var(--ink-tertiary)",
        },
        wax: {
          seal: "var(--wax-seal)",
          warm: "var(--wax-warm)",
          deep: "var(--wax-deep)",
          gold: "var(--wax-gold)",
          sage: "var(--wax-sage)",
        },
      },
      fontSize: {
        "annap-display": [
          "var(--text-display)",
          {
            lineHeight: "var(--leading-display)",
            letterSpacing: "var(--tracking-display)",
          },
        ],
        "annap-title": [
          "var(--text-title)",
          { lineHeight: "1.2", letterSpacing: "var(--tracking-display)" },
        ],
        "annap-narrative": [
          "var(--text-narrative)",
          {
            lineHeight: "var(--leading-narrative)",
            letterSpacing: "var(--tracking-narrative)",
          },
        ],
        "annap-functional": [
          "var(--text-functional)",
          {
            lineHeight: "var(--leading-functional)",
            letterSpacing: "var(--tracking-functional)",
          },
        ],
        "annap-ghost": [
          "var(--text-ghost)",
          {
            lineHeight: "var(--leading-functional)",
            letterSpacing: "var(--tracking-ghost)",
          },
        ],
      },
      spacing: {
        "annap-0": "var(--annap-space-0)",
        "annap-px": "var(--annap-space-px)",
        "annap-1": "var(--annap-space-1)",
        "annap-2": "var(--annap-space-2)",
        "annap-3": "var(--annap-space-3)",
        "annap-4": "var(--annap-space-4)",
        "annap-5": "var(--annap-space-5)",
        "annap-6": "var(--annap-space-6)",
        "annap-8": "var(--annap-space-8)",
        "annap-10": "var(--annap-space-10)",
        "annap-12": "var(--annap-space-12)",
        "annap-16": "var(--annap-space-16)",
        "annap-20": "var(--annap-space-20)",
        "annap-24": "var(--annap-space-24)",
        "annap-micro": "var(--space-micro)",
        "annap-small": "var(--space-small)",
        "annap-line": "var(--space-line)",
        "annap-paragraph": "var(--space-paragraph)",
        "annap-section": "var(--space-section)",
        "annap-page": "var(--space-page)",
        "annap-silence": "var(--space-silence)",
        "annap-inset": "var(--inset-content)",
        "annap-inset-narrow": "var(--inset-narrow)",
      },
      zIndex: {
        "annap-below": "var(--annap-z-below)",
        "annap-ambient": "var(--annap-z-ambient)",
        "annap-content": "var(--annap-z-content)",
        "annap-raised": "var(--annap-z-raised)",
        "annap-header": "var(--annap-z-header)",
        "annap-floating": "var(--annap-z-floating)",
        "annap-overlay": "var(--annap-z-overlay)",
        "annap-modal": "var(--annap-z-modal)",
        "annap-debug": "var(--annap-z-debug)",
        "annap-boot": "var(--annap-z-boot)",
        "sheet-desk": "var(--z-desk)",
        "sheet-paper": "var(--z-paper)",
        "sheet-content": "var(--z-content)",
        "sheet-marker": "var(--z-marker)",
        "sheet-vellum": "var(--z-vellum)",
        "sheet-envelope": "var(--z-envelope)",
        "sheet-arrival": "var(--z-arrival)",
        "sheet-system": "var(--z-system)",
      },
      transitionTimingFunction: {
        "annap-out": "var(--annap-ease-out)",
        "annap-enter": "var(--annap-ease-enter)",
        "annap-soft": "var(--annap-ease-soft)",
        "annap-room": "var(--annap-ease-room)",
        unfold: "var(--ease-unfold)",
        fold: "var(--ease-fold)",
        press: "var(--ease-press)",
      },
      transitionDuration: {
        ink: "var(--duration-ink)",
        rustle: "var(--duration-rustle)",
        turn: "var(--duration-turn)",
        open: "var(--duration-open)",
        seal: "var(--duration-seal)",
        breathe: "var(--duration-breathe)",
      },
      borderRadius: {
        "annap-none": "var(--radius-none)",
        "annap-subtle": "var(--radius-subtle)",
        "annap-paper": "var(--radius-paper)",
        "annap-panel": "var(--radius-panel)",
        "annap-envelope": "var(--radius-envelope)",
      },
      boxShadow: {
        "annap-paper": "var(--shadow-paper)",
        "annap-lifted": "var(--shadow-lifted)",
        "annap-envelope": "var(--shadow-envelope)",
      },
    },
  },
  plugins: [],
};
